version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: djayos/reverse-todo-list-backend:latest
    container_name: backend
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/reverse_todo
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: djayos/reverse-todo-list-frontend:latest
    container_name: frontend
    ports:
      - "3000:5000"
    depends_on:
      - backend
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
