name: CI - Dev Branch Workflow

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer toutes les branches
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Installer les dépendances Backend
      - name: Install Dependencies - Backend
        run: |
          cd backend
          npm install

      # 3. Réinstaller les dépendances Backend (optionnel)
      - name: Clean and Install Dependencies - Backend
        run: |
          cd backend
          rm -rf node_modules
          npm install

      # 4. Corriger les permissions Jest
      - name: Fix Jest Permissions
        run: |
          cd backend
          chmod +x ./node_modules/.bin/jest

      # 5. Exécuter les tests Backend
      - name: Run Tests - Backend
        run: |
          cd backend
          npx jest

      # 6. Installer les dépendances Frontend
      - name: Install Dependencies - Frontend
        run: |
          cd frontend
          npm install

      # 7. Exécuter les tests Frontend
      - name: Run Tests - Frontend
        run: |
          cd frontend
          npm test

      # 8. Configurer Git (nécessaire pour effectuer un push)
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # 9. Push dev dans main (via commit direct)
      - name: Push dev to main
        run: |
          git fetch origin main:main # Assure que main est récupérée
          git checkout main
          git merge dev
          git push origin main
