name: CI - Dev Branch Workflow

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Étape 2 : Installer les dépendances Backend
      - name: Install Dependencies - Backend
        run: |
          cd backend
          npm install

      # Étape 3 : Réinstaller les dépendances Backend (optionnel)
      - name: Clean and Install Dependencies - Backend
        run: |
          cd backend
          rm -rf node_modules
          npm install

      # Étape 4 : Corriger les permissions Jest
      - name: Fix Jest Permissions
        run: |
          cd backend
          chmod +x ./node_modules/.bin/jest

      # Étape 5 : Exécuter les tests Backend
      - name: Run Tests - Backend
        run: |
          cd backend
          npx jest

      # Étape 6 : Installer les dépendances Frontend
      - name: Install Dependencies - Frontend
        run: |
          cd frontend
          npm install

      # Étape 7 : Exécuter les tests Frontend
      - name: Run Tests - Frontend
        run: |
          cd frontend
          npm test

      # Étape 8 : Configurer Git (nécessaire pour effectuer un push)
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Étape 9 : Fusionner dev dans main (via commit direct)
      - name: Push dev to main
        run: |
          git checkout main
          git merge dev
          git push origin main
