name: CI - Dev Branch Workflow

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Étape 2 : Installer les dépendances
      - name: Install Dependencies - Backend
        run: |
          cd backend
          npm install

      - name: Install Dependencies - Frontend
        run: |
          cd frontend
          npm install

      # Étape 3 : Exécuter les tests unitaires
      - name: Run Tests - Backend
        run: |
          cd backend
          npm test

      - name: Run Tests - Frontend
        run: |
          cd frontend
          npm test

      # Étape 4 : Fusionner dev dans main si les tests réussissent
      - name: Merge dev into main
        uses: peter-evans/create-pull-request@v5
        with:
          branch: main
          commit-message: "Merge dev into main via CI"
          title: "Merge dev into main"
          body: "This merge was triggered automatically by the dev branch workflow."
          labels: merge
