name: CI/CD - Main Branch Workflow

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["CI - Dev Branch Workflow"]
    types:
      - completed

permissions:
  contents: write

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Installer Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # 2. Checkout du code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 3. Installer les dépendances Backend
      - name: Install Dependencies - Backend
        run: |
          cd backend
          npm install

      # 4. Exécuter les tests Backend
      - name: Run Tests - Backend
        run: |
          cd backend
          npx jest

      # 5. Installer les dépendances Frontend
      - name: Install Dependencies - Frontend
        run: |
          cd frontend
          npm install

      # 6. Exécuter les tests Frontend
      - name: Run Tests - Frontend
        run: |
          cd frontend
          npm test

      # 7. Construire les images Docker
      - name: Build Docker Images
        run: |
          docker-compose build

      # 8. Pousser les images Docker sur Docker Hub
      - name: Push Docker Images to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push djayos/reverse-todo-list-frontend:latest
          docker push djayos/reverse-todo-list-backend:latest
